---
active_modules: [pygments, tags, blog, disqus, latex, videos, iframe]
author: Danilo Bargen
canonical_url: http://blog.dbrgn.ch/
modules:
    pygments:
        style: tango
    disqus:
        shortname: dbrgn
language: en
